---

name: on-push workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
  # updates to specific parts of the  project should not trigger an action:
  # paths-ignore:
  #    - 'docs/**'


jobs:
  build_test_img:
    name: build the test-image
    runs-on: ubuntu-latest
    # Map a step output to a job output
    # outputs:
    #  output1: ${{ steps.step1.outputs.test }}
    steps:
      # - id: step1 --only one '-' pr step
      - name: clone into /action_test
        shell: bash
        run: git clone https://github.com/emTestAcc/action_test
      - name: tmp test statement
        shell: bash
        run: ls
      - name: run create_image.sh
        shell: bash
        run: |
          cd action_test/
          ./create_image.sh
      - name: something failed
        shell: bash
        run: echo "oh shit"
        if: failure()
