---

name: california-dreaming

on:
  push:
    branches:
      - main
  workflow_dispatch:
  # updates to specific parts of the  project should not trigger an action:
  # paths-ignore:
  #    - 'docs/**'


jobs:
  mytest:
    runs-on: ubuntu-latest
    shell: bash
    # Map a step output to a job output
    #outputs:
    #  output1: ${{ steps.step1.outputs.test }}
    steps:
      - id: step1
      - name: my step in the middel of the street
        run: /create_image.sh
