---
# WATCH OUT! This shit is super indentation-sensetive
name: on-push workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
  # updates to specific parts of the  project should not trigger an action:
  # paths-ignore:
  #    - 'docs/**'


jobs:
  build_test_img:
    name: build the test-image
    runs-on: ubuntu-latest
    # Map a step output to a job output
    # outputs:
    #  output1: ${{ steps.step1.outputs.test }}
    steps:
      # - id: step1 --only one '-' pr step
      - name: clone into /action_test
        shell: bash
        run: git clone https://github.com/emTestAcc/action_test
      - name: tmp test statement
        shell: bash
        run: ls
      - name: tmp test statement 2
        shell: bash
        run: ls ../../
      - name: run create_image.sh
        shell: bash
        run: |
          cd action_test/
          ./create_image.sh
      - name: something failed
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: tmpmail11223344@gmail.com
          password: kamel094salt
          subject: Something went wrong in the previous action
          # Literal body:
          body: Following is the output of log??
          # Read file contents as body:
          # body: file://README.md
          to: flh@energymachines.com
          from: tmpmail11223344@gmail.com
          # Optional carbon copy recipients
          # cc: kyloren@example.com,leia@example.com
          # Optional blind carbon copy recipients
          # bcc: r2d2@example.com,hansolo@example.com
          # Optional content type (defaults to text/plain):
          content_type: text/html
          # Optional converting Markdown to HTML
          convert_markdown: true
          # Optional attachments:
          # attachments: attachments.zip,git.diff,./dist/static/main.js
        if: failure()
      - name: save image
        run: |
          mkdir docker_img
          docker save em_img > docker_img/docker-image.tar
      - uses: actions/upload-artifact@v2
        with:
          name: docker-artifact
          path: docker_img
  load_docker_img:
    name: load pre_build image
    runs-on: ubuntu-latest
    needs: build_test_img
    steps:
      - name: Download Docker Image (Artifact)
        uses: actions/download-artifact@v2
        with:
          name: docker-artifact
          path: docker_img
